default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: activity_tracker_development

test:
  <<: *default
  database: activity_tracker_test

production:
  <<: *default
  database: activity_tracker_production
  username: "Brijesh_Rajput"
  password: "***34645"
